# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: light.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='light.proto',
  package='light',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0blight.proto\x12\x05light\"\x1e\n\x0clightRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1d\n\nlightReply\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\x05Light\x12\x32\n\x06turnOn\x12\x13.light.lightRequest\x1a\x11.light.lightReply\"\x00\x62\x06proto3'
)




_LIGHTREQUEST = _descriptor.Descriptor(
  name='lightRequest',
  full_name='light.lightRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='light.lightRequest.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_LIGHTREPLY = _descriptor.Descriptor(
  name='lightReply',
  full_name='light.lightReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='light.lightReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['lightRequest'] = _LIGHTREQUEST
DESCRIPTOR.message_types_by_name['lightReply'] = _LIGHTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

lightRequest = _reflection.GeneratedProtocolMessageType('lightRequest', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTREQUEST,
  '__module__' : 'light_pb2'
  # @@protoc_insertion_point(class_scope:light.lightRequest)
  })
_sym_db.RegisterMessage(lightRequest)

lightReply = _reflection.GeneratedProtocolMessageType('lightReply', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTREPLY,
  '__module__' : 'light_pb2'
  # @@protoc_insertion_point(class_scope:light.lightReply)
  })
_sym_db.RegisterMessage(lightReply)



_LIGHT = _descriptor.ServiceDescriptor(
  name='Light',
  full_name='light.Light',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=85,
  serialized_end=144,
  methods=[
  _descriptor.MethodDescriptor(
    name='turnOn',
    full_name='light.Light.turnOn',
    index=0,
    containing_service=None,
    input_type=_LIGHTREQUEST,
    output_type=_LIGHTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIGHT)

DESCRIPTOR.services_by_name['Light'] = _LIGHT

# @@protoc_insertion_point(module_scope)
