# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import light_pb2 as light__pb2


class LightStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.turnOn = channel.unary_unary(
        '/light.Light/turnOn',
        request_serializer=light__pb2.lightRequest.SerializeToString,
        response_deserializer=light__pb2.lightReply.FromString,
        )


class LightServicer(object):
  """The greeting service definition.
  """

  def turnOn(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LightServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'turnOn': grpc.unary_unary_rpc_method_handler(
          servicer.turnOn,
          request_deserializer=light__pb2.lightRequest.FromString,
          response_serializer=light__pb2.lightReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'light.Light', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
